# model_list:
#   - model_name: gpt-4
#     litellm_params:
#       model: openai/gpt-4

# general_settings:
#   master_key: os.environ/LITELLM_MASTER_KEY
#   database_url: os.environ/DATABASE_URL

model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4

general_settings:
  master_key: sk-password123
  database_url: "postgresql://postgres:V24oodFmIui45zw4@db.ncixeikhszfeyoznmvmv.supabase.co:5432/postgres?sslmode=require"