model_list:
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4

general_settings:
  master_key: sk-password123
  database_url: "postgresql://postgres.lqskuekltuzojsjekpeb:GcT2uHkQxrUOjDcW@aws-0-us-west-2.pooler.supabase.com:6543/postgres"
